version: "3.9"
    
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
          - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - db
    volumes:
      wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  web:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
      - certbotdata:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email aric.dev@mcast.edu.mt --agree-tos --no-eff-email -d test.aric-mcast.dev
    volumes:
        - certbotdata:/etc/letsencrypt
        - wordpress:/var/www/html

volumes:
  wordpress:
  dbdata:
  certbotdata: